spring:
  main.web-application-type: none
  threads.virtual.enabled: true
  application.name: pillarbox-monitoring-transfer
  jackson.deserialization:
    fail-on-null-for-primitives: true

pillarbox.monitoring:
  dispatch.uri: "http://localhost:8080/events"
  opensearch.uri: "http://localhost:9200"
