name: Quality

on:
  merge_group:
  pull_request:
    branches: [ main ]

jobs:
  quality:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      pull-requests: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: '24'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f # v6

      - name: Run Build
        run: ./gradlew build

      - name: Add coverage to PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: madrapps/jacoco-report@50d3aff4548aa991e6753342d9ba291084e63848 # v1.7.2
        with:
          paths: ${{ github.workspace }}/**/build/reports/kover/report.xml
          token: ${{ secrets.GITHUB_TOKEN }}
          update-comment: true
          title: Coverage Report
          min-coverage-changed-files: 0
          min-coverage-overall: 0

      - name: Build Docker image
        run: docker build -t pillarbox-monitoring-transfer .
